global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
     - targets: ["node-exporter:9100"]

  - job_name: "pushgateway"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
     - targets: ["pushgateway:9091"]

  - job_name: "alertmanager"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
     - targets: ["alertmanager:9093"]
